[package]
name = "clang-rs-example"
version = "0.1.0"
authors = ["Jonas Greitemann <jgreitemann@gmail.com>"]
edition = "2018"

[dependencies]
clang = {version = "1.0.3", features = ["clang_7_0"] }
itertools = "0.10.1"
